### ISSUE TITLE
Inquiry Regarding Storage and Handling of ViT Feature Data

### ISSUE THREAD

**Issue by andongBlue** [DeepLearnXMU/BigVideo-VMT#2]
Dear BigVideo Team,

I hope this message finds you well. First of all, I would like to extend my gratitude for the effort and resources you have invested in developing and providing the ViT feature data. It's an invaluable asset to the community, and I am excited to be utilizing it in my work.

I am reaching out to inquire about the specific practices you employed for storing and handling the ViT data, especially considering its substantial size. As of now, I have observed that the train datasets in their compressed form already occupy around 243GB. This poses a significant challenge in terms of storage and computational efficiency during the training process.

Could you kindly share some insights or recommendations on how to effectively manage and process such large datasets? Any details about your approach to data storage, or strategies to streamline the training process would be immensely helpful.

I understand that managing large-scale data can be complex, and any guidance you can offer from your experience would be greatly appreciated.

Thank you for your time and assistance. I am looking forward to your response and any advice you can provide.

Best regards,

**Comment by fringe-k** [comment]
Thanks for your attention to our work. All data is stored in our nas storage and hdfs system. The process procedure are modified from [VideoSwin](https://github.com/SwinTransformer/Video-Swin-Transformer/blob/master/docs/data_preparation.md#extract-frames) and [Hero_extractor](https://github.com/linjieli222/HERO_Video_Feature_Extractor). You can find an example under fairseq_mmt/scrpits/video_extractor/vit. Specifically, we first preprocess frames into a tsv file (like videoswin), where each row is related to a series of frames of a video. Our raw_dataset.py presents how we read and process each line. The feature extraction on Vit can be found in extract_by_shard.py. We do extraction on a V-100 GPU so that the speed is fast. We also add a ShardSampler so that we can synchronously run the sh file by shard (with --shard_id). Hope this can help you.

**Comment by andongBlue** [comment]
thx~!
